// AUTO-GENERATED by scripts/sync-docs-releases.mjs — do not hand-edit.
// Regenerate with: bun run guides:sync
export type ReleaseKind = 'latest' | 'major' | 'minor';

export interface Release {
  /** Full version label, e.g. "2.15.0". */
  version: string;
  kind: ReleaseKind;
  /** Human-readable date, e.g. "September 13, 2026". */
  date: string;
  /** Git tag backing this release, e.g. "v2.15.0". */
  tag: string;
  /** One or two sentences framing the release. */
  summary: string;
  /** Checklist of what the release brought. */
  highlights: string[];
}

export const releases: Release[] = [
  {
    version: '5.1.0',
    kind: 'latest',
    date: 'September 24, 2026',
    tag: 'v5.1.0',
    summary: '**insforge:** Add database fallback, storage and functions adapter',
    highlights: [
      '**insforge:** Add database fallback, storage and functions adapter',
      '**wordpress,notion:** Validate API responses and inputs with Zod',
      '**validation:** Cover core, access, WordPress and Notion with Zod',
      '**notion:** Add changes to 3 files',
      '**validation:** Add Zod schemas with inferred types library-wide',
      '**media:** Add SmartVideo and YouTube channel services',
    ],
  },
  {
    version: '5.0.1',
    kind: 'minor',
    date: 'September 22, 2026',
    tag: 'v5.0.1',
    summary: '**guides:** Update dependencies or build settings in 2 files',
    highlights: [
      '**guides:** Update dependencies or build settings in 2 files',
    ],
  },
  {
    version: '5.0.0',
    kind: 'major',
    date: 'September 22, 2026',
    tag: 'v5.0.0',
    summary: 'Release 5.0.0 — see the release notes for details.',
    highlights: [
      'See the full release notes on GitHub for details.',
    ],
  },
  {
    version: '4.0.4',
    kind: 'minor',
    date: 'September 22, 2026',
    tag: 'v4.0.4',
    summary: 'Release 4.0.4 — see the release notes for details.',
    highlights: [
      'See the full release notes on GitHub for details.',
    ],
  },
  {
    version: '4.0.3',
    kind: 'minor',
    date: 'September 22, 2026',
    tag: 'v4.0.3',
    summary: '**katanakit-js:** Add framework-free vanilla query adapter and examples',
    highlights: [
      '**katanakit-js:** Add framework-free vanilla query adapter and examples',
      '**katanakit-js:** Run the query layer on TanStack Query Core',
      'Add interactive playground (Vue 3 + Vite + Vue Router)',
      '**wordpress:** Add _fields, _embed, ACF support + Vue/Nuxt examples',
      '**adapters:** Add Notion and WordPress REST API adapters with framework examples',
      '**vue:** Add generic useKatanaWatch/useWatch with native watch props',
    ],
  },
  {
    version: '4.0.2',
    kind: 'minor',
    date: 'September 22, 2026',
    tag: 'v4.0.2',
    summary: 'Release 4.0.2 — see the release notes for details.',
    highlights: [
      'See the full release notes on GitHub for details.',
    ],
  },
  {
    version: '4.0.1',
    kind: 'minor',
    date: 'September 22, 2026',
    tag: 'v4.0.1',
    summary: '**katanakit-js:** Add Bun server adapter with dummyjson demo routes',
    highlights: [
      '**katanakit-js:** Add Bun server adapter with dummyjson demo routes',
      '**katanakit-js:** Address code review and security findings',
      '**katanakit-js:** Address Bun adapter code review findings',
      '**katanakit-js:** Rename docs to guides, configure prettier+eslint tooling',
      '**katanakit-js:** Simplify logger to useLogger(message, data, level)',
      '**katanakit-js:** Document fixes, logger refactor and guides rename in CHANGELOG',
    ],
  },
  {
    version: '4.0.0',
    kind: 'major',
    date: 'September 20, 2026',
    tag: 'v4.0.0',
    summary: '**katanakit-js:** Add useRequest and useWatch to framework adapters',
    highlights: [
      '**katanakit-js:** Add useRequest and useWatch to framework adapters',
      '**katanakit-js:** Add React, Solid, Svelte and Angular adapters',
      '**katanakit-js:** Correct query cache, SSR-safety, SSRF and adapter bugs',
      'Subcarpetas como archivos normales',
      '**katanakit-js:** Update dependencies or build settings in 2 files',
      '**katanakit-js:** Bump to v4.0.0 and point repo refs to the katanakit monorepo',
    ],
  },
];
