// AUTO-GENERATED by scripts/sync-docs-releases.mjs — do not hand-edit.
// Regenerate with: bun run guides:sync
export type ReleaseKind = 'latest' | 'major' | 'minor';

export interface Release {
  /** Full version label, e.g. "2.15.0". */
  version: string;
  kind: ReleaseKind;
  /** Human-readable date, e.g. "September 13, 2026". */
  date: string;
  /** Git tag backing this release, e.g. "v2.15.0". */
  tag: string;
  /** One or two sentences framing the release. */
  summary: string;
  /** Checklist of what the release brought. */
  highlights: string[];
}

export const releases: Release[] = [
  {
    version: '4.0.2',
    kind: 'latest',
    date: 'September 22, 2026',
    tag: 'v4.0.2',
    summary: 'Release 4.0.2 — see the release notes for details.',
    highlights: [
      'See the full release notes on GitHub for details.',
    ],
  },
  {
    version: '4.0.1',
    kind: 'minor',
    date: 'September 22, 2026',
    tag: 'v4.0.1',
    summary: '**katanakit-js:** Add Bun server adapter with dummyjson demo routes',
    highlights: [
      '**katanakit-js:** Add Bun server adapter with dummyjson demo routes',
      '**katanakit-js:** Address code review and security findings',
      '**katanakit-js:** Address Bun adapter code review findings',
      '**katanakit-js:** Rename docs to guides, configure prettier+eslint tooling',
      '**katanakit-js:** Simplify logger to useLogger(message, data, level)',
      '**katanakit-js:** Document fixes, logger refactor and guides rename in CHANGELOG',
    ],
  },
  {
    version: '4.0.0',
    kind: 'major',
    date: 'September 20, 2026',
    tag: 'v4.0.0',
    summary: '**katanakit-js:** Add useRequest and useWatch to framework adapters',
    highlights: [
      '**katanakit-js:** Add useRequest and useWatch to framework adapters',
      '**katanakit-js:** Add React, Solid, Svelte and Angular adapters',
      '**katanakit-js:** Correct query cache, SSR-safety, SSRF and adapter bugs',
      'Subcarpetas como archivos normales',
      '**katanakit-js:** Update dependencies or build settings in 2 files',
      '**katanakit-js:** Bump to v4.0.0 and point repo refs to the katanakit monorepo',
    ],
  },
  {
    version: '3.2.4',
    kind: 'minor',
    date: 'September 18, 2026',
    tag: 'v3.2.4',
    summary: 'Improve useBuildUrl, Kitt, and contribution guide',
    highlights: [
      'Improve useBuildUrl, Kitt, and contribution guide',
    ],
  },
  {
    version: '3.2.2',
    kind: 'minor',
    date: 'September 18, 2026',
    tag: 'v3.2.2',
    summary: 'Release 3.2.2 — see the release notes for details.',
    highlights: [
      'See the full release notes on GitHub for details.',
    ],
  },
  {
    version: '3.2.1',
    kind: 'minor',
    date: 'September 18, 2026',
    tag: 'v3.2.1',
    summary: '**wordpress:** Add _fields, _embed, ACF support + Vue/Nuxt examples',
    highlights: [
      '**wordpress:** Add _fields, _embed, ACF support + Vue/Nuxt examples',
      '**adapters:** Add Notion and WordPress REST API adapters with framework examples',
      '**readme:** Add Notion/WordPress adapter documentation with _fields, _embed, ACF',
      '**changelog:** Add _fields, _embed, ACF and Vue/Nuxt entries',
    ],
  },
  {
    version: '3.1.4',
    kind: 'minor',
    date: 'September 18, 2026',
    tag: 'v3.1.4',
    summary: '**README.md:** Update documentation in 14 files',
    highlights: [
      '**README.md:** Update documentation in 14 files',
      '**wordpress:** Update 2 files',
    ],
  },
  {
    version: '3.1.3',
    kind: 'minor',
    date: 'September 16, 2026',
    tag: 'v3.1.3',
    summary: 'Release 3.1.3 — see the release notes for details.',
    highlights: [
      'See the full release notes on GitHub for details.',
    ],
  },
];
