export type {
	IfConfig,
	IfInsertRows,
	IfInvokeOptions,
	IfListOptions,
	IfOrder,
	IfRpcCall,
	IfStorageRef,
	IfTableQuery,
	IfUpdatePatch,
	IfWriteQuery,
} from "../../types/index.js";
export {
	useGetInsforgeClient,
	useIfDelete,
	useIfDownload,
	useIfGetPublicUrl,
	useIfInsert,
	useIfInvokeFunction,
	useIfListObjects,
	useIfRemove,
	useIfRpc,
	useIfSelect,
	useIfUpdate,
	useIfUpload,
	useInitInsforge,
} from "./insforge.service.js";
