// AUTO-GENERATED by scripts/sync-docs-releases.mjs — do not hand-edit.
// Regenerate with: pnpm docs:sync
export type ReleaseKind = 'latest' | 'major' | 'minor';

export interface Release {
  /** Full version label, e.g. "2.15.0". */
  version: string;
  kind: ReleaseKind;
  /** Human-readable date, e.g. "September 13, 2026". */
  date: string;
  /** Git tag backing this release, e.g. "v2.15.0". */
  tag: string;
  /** One or two sentences framing the release. */
  summary: string;
  /** Checklist of what the release brought. */
  highlights: string[];
}

export const releases: Release[] = [
  {
    version: '3.2.4',
    kind: 'latest',
    date: 'September 18, 2026',
    tag: 'v3.2.4',
    summary: 'Improve useBuildUrl, Kitt, and contribution guide',
    highlights: [
      'Improve useBuildUrl, Kitt, and contribution guide',
    ],
  },
  {
    version: '3.2.1',
    kind: 'minor',
    date: 'September 18, 2026',
    tag: 'v3.2.1',
    summary: '**wordpress:** Add _fields, _embed, ACF support + Vue/Nuxt examples',
    highlights: [
      '**wordpress:** Add _fields, _embed, ACF support + Vue/Nuxt examples',
      '**adapters:** Add Notion and WordPress REST API adapters with framework examples',
      '**readme:** Add Notion/WordPress adapter documentation with _fields, _embed, ACF',
      '**changelog:** Add _fields, _embed, ACF and Vue/Nuxt entries',
    ],
  },
  {
    version: '3.1.4',
    kind: 'minor',
    date: 'September 18, 2026',
    tag: 'v3.1.4',
    summary: '**README.md:** Update documentation in 14 files',
    highlights: [
      '**README.md:** Update documentation in 14 files',
      '**wordpress:** Update 2 files',
    ],
  },
  {
    version: '3.1.1',
    kind: 'minor',
    date: 'September 16, 2026',
    tag: 'v3.1.1',
    summary: 'Sync release cards for v3.1.0',
    highlights: [
      'Sync release cards for v3.1.0',
    ],
  },
  {
    version: '3.1.0',
    kind: 'minor',
    date: 'September 14, 2026',
    tag: 'v3.1.0',
    summary: '**vue:** Add generic useKatanaWatch/useWatch with native watch props',
    highlights: [
      '**vue:** Add generic useKatanaWatch/useWatch with native watch props',
      'Sync release cards for v3.0.1',
    ],
  },
  {
    version: '3.0.1',
    kind: 'minor',
    date: 'September 13, 2026',
    tag: 'v3.0.1',
    summary: 'Address v3.0.0 audit findings',
    highlights: [
      'Address v3.0.0 audit findings',
      '**changelog:** Fold unreleased 2.15.1 entry into 3.0.0',
      'Sync release cards for v3.0.0',
      '**BREAKING** Migrate from Yarn 4 to pnpm 12',
    ],
  },
  {
    version: '3.0.0',
    kind: 'major',
    date: 'September 13, 2026',
    tag: 'v3.0.0',
    summary: 'Add access-control service and rename Prisma User to Account',
    highlights: [
      'Add access-control service and rename Prisma User to Account',
      '**docs:** Automate release cards, changelog and navbar from git tags',
      'Clarify merge-into-dev-first workflow',
    ],
  },
  {
    version: '2.15.0',
    kind: 'minor',
    date: 'September 13, 2026',
    tag: 'v2.15.0',
    summary: 'Add QueryClient with cache, retry, dedup and Vue composables',
    highlights: [
      'Add QueryClient with cache, retry, dedup and Vue composables',
      'Add CI fail-fast entry to CHANGELOG',
      'Add QueryClient guide and update sidebar',
      'Add Husky pre-commit, AGENTS.md, CI fail-fast',
      'Replace Biome with ESLint + Prettier',
      'Remove AI tool artifacts and refresh README links',
    ],
  },
];
