// AUTO-GENERATED by scripts/sync-docs-releases.mjs — do not hand-edit.
// Regenerate with: pnpm docs:sync
export type ReleaseKind = 'latest' | 'major' | 'minor';

export interface Release {
  /** Full version label, e.g. "2.15.0". */
  version: string;
  kind: ReleaseKind;
  /** Human-readable date, e.g. "September 13, 2026". */
  date: string;
  /** Git tag backing this release, e.g. "v2.15.0". */
  tag: string;
  /** One or two sentences framing the release. */
  summary: string;
  /** Checklist of what the release brought. */
  highlights: string[];
}

export const releases: Release[] = [
  {
    version: '3.1.0',
    kind: 'latest',
    date: 'September 14, 2026',
    tag: 'v3.1.0',
    summary: '**vue:** Add generic useKatanaWatch/useWatch with native watch props',
    highlights: [
      '**vue:** Add generic useKatanaWatch/useWatch with native watch props',
      'Sync release cards for v3.0.1',
    ],
  },
  {
    version: '3.0.1',
    kind: 'minor',
    date: 'September 13, 2026',
    tag: 'v3.0.1',
    summary: 'Address v3.0.0 audit findings',
    highlights: [
      'Address v3.0.0 audit findings',
      '**changelog:** Fold unreleased 2.15.1 entry into 3.0.0',
      'Sync release cards for v3.0.0',
      '**BREAKING** Migrate from Yarn 4 to pnpm 12',
    ],
  },
  {
    version: '3.0.0',
    kind: 'major',
    date: 'September 13, 2026',
    tag: 'v3.0.0',
    summary: 'Add access-control service and rename Prisma User to Account',
    highlights: [
      'Add access-control service and rename Prisma User to Account',
      '**docs:** Automate release cards, changelog and navbar from git tags',
      'Clarify merge-into-dev-first workflow',
    ],
  },
  {
    version: '2.15.0',
    kind: 'minor',
    date: 'September 13, 2026',
    tag: 'v2.15.0',
    summary: 'Add QueryClient with cache, retry, dedup and Vue composables',
    highlights: [
      'Add QueryClient with cache, retry, dedup and Vue composables',
      'Add CI fail-fast entry to CHANGELOG',
      'Add QueryClient guide and update sidebar',
      'Add Husky pre-commit, AGENTS.md, CI fail-fast',
      'Replace Biome with ESLint + Prettier',
      'Remove AI tool artifacts and refresh README links',
    ],
  },
  {
    version: '2.14.2',
    kind: 'minor',
    date: 'September 13, 2026',
    tag: 'v2.14.2',
    summary: '**docs:** Replace navbar color mode toggle with switch',
    highlights: [
      '**docs:** Replace navbar color mode toggle with switch',
      '**release:** Generate sectioned release notes from conventional commits',
      '**changelog:** Add v2.14.2 release notes',
      '**ui-kit:** Add Katana UI design documentation',
      'Fix broken links in README with absolute GitHub URLs',
      'Add Releases dropdown to navbar with links to GitHub releases and tags',
    ],
  },
  {
    version: '2.14.1',
    kind: 'minor',
    date: 'September 10, 2026',
    tag: 'v2.14.1',
    summary: '**release:** Use npm publish instead of yarn npm publish for auth compatibility',
    highlights: [
      '**release:** Use npm publish instead of yarn npm publish for auth compatibility',
      'Improve API manager documentation with real-world examples and runnable demo',
      'Harden supply chain security — pin deps, add resolutions, add socket.yml',
    ],
  },
  {
    version: '2.14.0',
    kind: 'minor',
    date: 'September 10, 2026',
    tag: 'v2.14.0',
    summary: '**docs:** Resolve yarn workspace lockfile conflict and typedoc compatibility',
    highlights: [
      '**docs:** Resolve yarn workspace lockfile conflict and typedoc compatibility',
      'Clean up unused imports, test formatting, and type safety',
      '**changelog:** Add v2.14.0 release notes',
      '**.codegraph:** Update pipeline configuration in 44 files',
    ],
  },
  {
    version: '2.13.5',
    kind: 'minor',
    date: 'September 9, 2026',
    tag: 'v2.13.5',
    summary: '**package.json:** Update dependencies or build settings in package.json',
    highlights: [
      '**package.json:** Update dependencies or build settings in package.json',
    ],
  },
];
