import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { defineConfig } from "vitepress";

const API_SIDEBAR = fileURLToPath(new URL("../api/typedoc-sidebar.json", import.meta.url));

type SidebarItem = { text: string; link?: string; items?: SidebarItem[]; collapsed?: boolean };

/**
 * Generated by `typedoc-vitepress-theme` during `bun run docs:prepare`.
 * Falls back to a single link so a fresh clone can still boot VitePress.
 */
const apiSidebar: SidebarItem[] = existsSync(API_SIDEBAR)
	? (JSON.parse(readFileSync(API_SIDEBAR, "utf8")) as SidebarItem[])
	: [{ text: "Overview", link: "/api/" }];

export default defineConfig({
	title: "KatanaKit",
	description:
		"A sharp, framework-agnostic TypeScript service toolkit organized with hexagonal architecture.",
	base: "/",
	cleanUrls: true,
	lastUpdated: true,
	sitemap: { hostname: "https://docs.senseikatana.com" },
	head: [["meta", { name: "theme-color", content: "#0a0a0a" }]],
	vite: {
		resolve: {
			alias: {
				"@katanakit/ui/styles.css": fileURLToPath(
					new URL("../../packages/ui/dist/styles.css", import.meta.url),
				),
				"@katanakit/ui": fileURLToPath(new URL("../../packages/ui/dist/index.js", import.meta.url)),
			},
		},
		build: {
			// The largest chunk is the lazily-loaded local search index (full-text of
			// ~780 pages, API reference included); the limit only keeps the build
			// output warning-free.
			chunkSizeWarningLimit: 2048,
		},
	},
	themeConfig: {
		nav: [
			{ text: "Home", link: "/" },
			{ text: "Guides", link: "/guides/getting-started", activeMatch: "/guides/" },
			{ text: "UI Kit", link: "/ui-kit/", activeMatch: "/ui-kit/" },
			{ text: "Releases", link: "/changelog" },
			{ text: "API Reference", link: "/api/" },
		],
		sidebar: [
			{ text: "Getting Started", link: "/guides/getting-started" },
			{
				text: "Guides",
				collapsed: false,
				items: [
					{ text: "Query Client", link: "/guides/query-client" },
					{ text: "Framework Adapters", link: "/guides/framework-adapters" },
					{ text: "Bun Adapter", link: "/guides/bun-adapter" },
					{ text: "Watch", link: "/guides/watch" },
					{ text: "Filesystem", link: "/guides/filesystem" },
					{ text: "Faker", link: "/guides/faker" },
					{ text: "Architecture", link: "/guides/architecture" },
					{ text: "Roadmap", link: "/guides/roadmap" },
				],
			},
			{
				text: "UI Kit",
				collapsed: true,
				items: [
					{ text: "Overview", link: "/ui-kit/" },
					{
						text: "Components",
						collapsed: false,
						items: [
							{ text: "Button", link: "/ui-kit/components/button" },
							{ text: "Input", link: "/ui-kit/components/input" },
							{ text: "Card", link: "/ui-kit/components/card" },
							{ text: "Badge", link: "/ui-kit/components/badge" },
							{ text: "Alert", link: "/ui-kit/components/alert" },
						],
					},
					{ text: "Architecture", link: "/ui-kit/architecture" },
					{ text: "Inventory", link: "/ui-kit/inventory" },
					{ text: "LLM Files", link: "/ui-kit/llm-files" },
					{ text: "Roadmap", link: "/ui-kit/roadmap" },
				],
			},
			{ text: "Releases", link: "/changelog" },
			{ text: "API Reference", collapsed: true, items: apiSidebar },
		],
		search: { provider: "local" },
		socialLinks: [{ icon: "github", link: "https://github.com/senseikatana/katanakit-js" }],
		editLink: {
			pattern: "https://github.com/senseikatana/katanakit-js/edit/dev/docs/:path",
			text: "Edit this page on GitHub",
		},
		footer: {
			message: "Released under the MIT License.",
			copyright: "Copyright © Sergio Jurado",
		},
	},
});
