import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import tailwindcss from "@tailwindcss/vite";
import { defineConfig, type HeadConfig } from "vitepress";

import { useSeoMeta } from "../../src/config/seo.service.js";
import type { SiteConfig } from "../../src/config/site.config.js";

const API_SIDEBAR = fileURLToPath(new URL("../api/typedoc-sidebar.json", import.meta.url));

const DOCS_ORIGIN = "https://docs.senseikatana.com";
const DOCS_OG_IMAGE = `${DOCS_ORIGIN}/images/social-card.jpg`;
const DOCS_KEYWORDS =
	"katanakit, typescript, hexagonal architecture, api, rest, graphql, safe results, zod, query client";

/** Docs site config consumed by the library's own SEO helpers (dogfooding). */
const docsSiteConfig: SiteConfig = {
	site: DOCS_ORIGIN,
	title: "KatanaKit",
	description:
		"A sharp, framework-agnostic TypeScript service toolkit organized with hexagonal architecture.",
	lang: "en-US",
	author: "Sergio Jurado",
	ogImage: DOCS_OG_IMAGE,
	rss: { enabled: false, path: "/rss.xml", limit: 20 },
	seo: { noindex: false, canonical: true, openGraph: true, twitterCard: true, jsonLd: true },
};

/** Canonical URL for a page (`index.md` maps to the section root). */
function pageUrl(relativePath: string): string {
	const clean = relativePath
		.replace(/(^|\/)index\.md$/, "$1")
		.replace(/\.md$/, "")
		.replace(/\/$/, "");
	return clean ? `${DOCS_ORIGIN}/${clean}` : `${DOCS_ORIGIN}/`;
}

/**
 * Post-processes the built HTML so every `<meta>` (plus canonical links and the
 * anti-FOUC inline scripts) sits right after `<title>`, before stylesheet links
 * and the app script. VitePress renders its `head` entries after the assets and
 * only offers `transformHtml` to reorder the final document.
 */
function reorderHead(html: string): string {
	const head = /<head>([\s\S]*?)<\/head>/.exec(html);
	if (!head) return html;

	const moved: string[] = [];
	let inner = head[1];

	inner = inner.replace(/<meta\b[^>]*>/g, (tag) => {
		if (/\bcharset\s*=/i.test(tag)) return tag;
		moved.push(tag);
		return "";
	});
	inner = inner.replace(/<link\b[^>]*rel="canonical"[^>]*>/g, (tag) => {
		moved.push(tag);
		return "";
	});
	inner = inner.replace(
		/<script (?:id="check-(?:dark-mode|mac-os)"|type="application\/ld\+json")[\s\S]*?<\/script>/g,
		(tag) => {
			moved.push(tag);
			return "";
		},
	);
	// Drop the whitespace-only lines the extracted tags leave behind.
	inner = inner.replace(/\n[ \t]+(?=\n)/g, "");

	if (moved.length === 0) return html;

	const titleEnd = inner.indexOf("</title>");
	const at = titleEnd === -1 ? inner.indexOf(">") + 1 : titleEnd + "</title>".length;
	const ordered = `${inner.slice(0, at)}\n    ${moved.join("\n    ")}\n${inner
		.slice(at)
		.replace(/^\s*\n/, "")}`;

	return html.replace(head[0], () => `<head>${ordered}</head>`);
}

type SidebarItem = { text: string; link?: string; items?: SidebarItem[]; collapsed?: boolean };

/**
 * Generated by `typedoc-vitepress-theme` during `bun run docs:prepare`.
 * Falls back to a single link so a fresh clone can still boot VitePress.
 */
const apiSidebar: SidebarItem[] = existsSync(API_SIDEBAR)
	? (JSON.parse(readFileSync(API_SIDEBAR, "utf8")) as SidebarItem[])
	: [{ text: "Overview", link: "/api/" }];

export default defineConfig({
	title: "KatanaKit",
	description:
		"A sharp, framework-agnostic TypeScript service toolkit organized with hexagonal architecture.",
	base: "/",
	cleanUrls: true,
	lastUpdated: true,
	sitemap: { hostname: "https://docs.senseikatana.com" },
	// Only tags the SEO helper cannot generate live here; the rest is per-page
	// (transformHead) and reordered to the top of <head> (transformHtml).
	head: [["meta", { name: "theme-color", content: "#0a0a0a" }]],
	transformHead({ pageData, title }) {
		const { tags } = useSeoMeta(
			{
				title,
				description: pageData.description || docsSiteConfig.description,
				keywords: DOCS_KEYWORDS,
				viewport: "width=device-width, initial-scale=1.0",
				canonical: pageUrl(pageData.relativePath),
				ogUrl: pageUrl(pageData.relativePath),
				ogType: "website",
			},
			docsSiteConfig,
		);

		const head: HeadConfig[] = [];
		for (const node of tags) {
			// VitePress already owns <title>; everything else is injected here.
			if (node.tag === "title") continue;
			head.push([node.tag, node.attrs ?? {}, node.text ?? ""]);
		}
		// useSeoMeta covers HTML + Open Graph only; Twitter cards layer on top.
		head.push(["meta", { name: "twitter:card", content: "summary_large_image" }]);
		head.push(["meta", { name: "twitter:image", content: DOCS_OG_IMAGE }]);

		return head;
	},
	transformHtml(code, id) {
		if (!id.endsWith(".html")) return code;
		return reorderHead(code);
	},
	vite: {
		plugins: [tailwindcss()],
		resolve: {
			alias: {
				"@katanakit/ui/styles.css": fileURLToPath(
					new URL("../../packages/ui/dist/styles.css", import.meta.url),
				),
				"@katanakit/ui": fileURLToPath(new URL("../../packages/ui/dist/index.js", import.meta.url)),
			},
		},
		build: {
			// The largest chunk is the lazily-loaded local search index (full-text of
			// ~780 pages, API reference included); the limit only keeps the build
			// output warning-free.
			chunkSizeWarningLimit: 2048,
		},
	},
	themeConfig: {
		nav: [
			{ text: "Home", link: "/" },
			{ text: "Guides", link: "/guides/getting-started", activeMatch: "^/guides/(?!upgrade-to)" },
			{ text: "Upgrade", link: "/guides/upgrade-to/", activeMatch: "^/guides/upgrade-to" },
			{ text: "UI Kit", link: "/ui-kit/", activeMatch: "^/ui-kit/" },
			{ text: "Releases", link: "/changelog" },
			{ text: "API Reference", link: "/api/" },
		],
		sidebar: [
			{ text: "Getting Started", link: "/guides/getting-started" },
			{
				text: "Guides",
				collapsed: false,
				items: [
					{ text: "Error Handling", link: "/guides/errors" },
					{ text: "Query Client", link: "/guides/query-client" },
					{ text: "Framework Adapters", link: "/guides/framework-adapters" },
					{ text: "Bun Adapter", link: "/guides/bun-adapter" },
					{ text: "Watch", link: "/guides/watch" },
					{ text: "Filesystem", link: "/guides/filesystem" },
					{ text: "Faker", link: "/guides/faker" },
					{ text: "PhotoSwipe", link: "/guides/photoswipe" },
					{ text: "Better Auth", link: "/guides/better-auth" },
					{ text: "Architecture", link: "/guides/architecture" },
					{ text: "Roadmap", link: "/guides/roadmap" },
				],
			},
			{
				text: "Upgrade Guides",
				collapsed: false,
				items: [
					{ text: "Overview", link: "/guides/upgrade-to/" },
					{ text: "Upgrade to v6", link: "/guides/upgrade-to/v6" },
					{ text: "Upgrade to v5", link: "/guides/upgrade-to/v5" },
					{ text: "Upgrade to v4", link: "/guides/upgrade-to/v4" },
					{ text: "Upgrade to v3", link: "/guides/upgrade-to/v3" },
					{ text: "Upgrade to v2", link: "/guides/upgrade-to/v2" },
				],
			},
			{
				text: "UI Kit",
				collapsed: true,
				items: [
					{ text: "Overview", link: "/ui-kit/" },
					{
						text: "Components",
						collapsed: false,
						items: [
							{ text: "Button", link: "/ui-kit/components/button" },
							{ text: "Input", link: "/ui-kit/components/input" },
							{ text: "Card", link: "/ui-kit/components/card" },
							{ text: "Badge", link: "/ui-kit/components/badge" },
							{ text: "Alert", link: "/ui-kit/components/alert" },
						],
					},
					{
						text: "SCSS framework",
						collapsed: true,
						items: [
							{ text: "Overview", link: "/ui-kit/css/" },
							{ text: "Getting Started", link: "/ui-kit/css/getting-started" },
							{
								text: "Core",
								collapsed: true,
								items: [
									{ text: "Design Tokens", link: "/ui-kit/css/core/tokens" },
									{ text: "Colors", link: "/ui-kit/css/core/colors" },
									{ text: "Breakpoints", link: "/ui-kit/css/core/breakpoints" },
									{ text: "Dark Mode", link: "/ui-kit/css/core/dark-mode" },
									{ text: "@apply", link: "/ui-kit/css/core/apply" },
								],
							},
							{
								text: "Mixins",
								collapsed: true,
								items: [
									{ text: "Grid", link: "/ui-kit/css/mixins/grid" },
									{ text: "Flexbox", link: "/ui-kit/css/mixins/flex" },
								],
							},
							{
								text: "Utilities",
								collapsed: true,
								items: [
									{ text: "Padding", link: "/ui-kit/css/utilities/padding" },
									{ text: "Margin", link: "/ui-kit/css/utilities/margin" },
									{ text: "Gap", link: "/ui-kit/css/utilities/gap" },
									{ text: "Display", link: "/ui-kit/css/utilities/display" },
									{ text: "Typography", link: "/ui-kit/css/utilities/typography" },
									{ text: "Effects", link: "/ui-kit/css/utilities/effects" },
									{ text: "Aspect Ratio", link: "/ui-kit/css/utilities/aspect-ratio" },
									{ text: "Object Fit & Position", link: "/ui-kit/css/utilities/object" },
									{ text: "Cursor", link: "/ui-kit/css/utilities/cursor" },
									{ text: "Visibility", link: "/ui-kit/css/utilities/visibility" },
									{ text: "Text Transform", link: "/ui-kit/css/utilities/text-transform" },
									{ text: "Text Decoration & Overflow", link: "/ui-kit/css/utilities/text-decoration" },
									{ text: "Line Height & Letter Spacing", link: "/ui-kit/css/utilities/line-height" },
									{ text: "Font Family", link: "/ui-kit/css/utilities/font-family" },
									{ text: "List Style", link: "/ui-kit/css/utilities/list-style" },
									{ text: "Interactivity", link: "/ui-kit/css/utilities/interactivity" },
									{ text: "Border Style", link: "/ui-kit/css/utilities/border-style" },
									{ text: "Float, Clear, Isolation & Box Sizing", link: "/ui-kit/css/utilities/float" },
									{ text: "Tables", link: "/ui-kit/css/utilities/tables" },
									{ text: "Grid Classes", link: "/ui-kit/css/utilities/grid-classes" },
									{ text: "Flex Classes", link: "/ui-kit/css/utilities/flex-classes" },
									{ text: "Container", link: "/ui-kit/css/utilities/container" },
									{ text: "Position Values", link: "/ui-kit/css/utilities/position-values" },
									{ text: "Overflow Direction", link: "/ui-kit/css/utilities/overflow-direction" },
									{ text: "Extended Colors", link: "/ui-kit/css/utilities/colors-extended" },
								],
							},
							{
								text: "Reference",
								collapsed: true,
								items: [
									{ text: "Functions", link: "/ui-kit/css/reference/functions" },
									{ text: "API Reference", link: "/ui-kit/css/reference/api-reference" },
									{ text: "Architecture", link: "/ui-kit/css/reference/architecture" },
								],
							},
						],
					},
					{ text: "Architecture", link: "/ui-kit/architecture" },
					{ text: "Inventory", link: "/ui-kit/inventory" },
					{ text: "LLM Files", link: "/ui-kit/llm-files" },
					{ text: "HyperUI", link: "/ui-kit/hyperui" },
					{ text: "Roadmap", link: "/ui-kit/roadmap" },
				],
			},
			{ text: "Releases", link: "/changelog" },
			{ text: "API Reference", collapsed: true, items: apiSidebar },
		],
		search: { provider: "local" },
		socialLinks: [],
		editLink: {
			pattern: "https://github.com/senseikatana/katanakit-js/edit/dev/docs/:path",
			text: "Edit this page on GitHub",
		},
		footer: {
			message: "Released under the MIT License.",
			copyright: "Copyright © Sergio Jurado",
		},
	},
});
