import type * as Preset from "@docusaurus/preset-classic";
import type { Config } from "@docusaurus/types";
import { themes as prismThemes } from "prism-react-renderer";
import typedocPluginWithEscapedApiDocs from "./plugin-typedoc-escape";

const config: Config = {
	title: "KatanaKit",
	tagline:
		"A sharp, framework-agnostic TypeScript service toolkit organized with hexagonal architecture.",
	favicon: "img/favicon.ico",

	future: {
		v4: true,
	},

	url: "https://docs.senseikatana.com",
	baseUrl: "/",

	organizationName: "senseikatana",
	projectName: "katanakit-js",
	trailingSlash: true,

	onBrokenLinks: "warn",
	markdown: {
		hooks: {
			onBrokenMarkdownLinks: "warn",
		},
	},

	i18n: {
		defaultLocale: "es",
		locales: ["en", "es"],
		path: "/",
	},

	plugins: [
		[
			typedocPluginWithEscapedApiDocs,
			{
				entryPoints: ["../src/index.ts"],
				tsconfig: "../tsconfig.json",
				out: "./content/api",
				cleanOutputDir: true,
				useHTMLEncodedBrackets: true,
			},
		],
	],

	presets: [
		[
			"classic",
			{
			docs: {
				path: "content",
				sidebarPath: "./sidebars.ts",
				editUrl: "https://github.com/senseikatana/katanakit-js/edit/dev/guides/content/",
			},
				blog: false,
				theme: {
					customCss: "./src/css/custom.css",
				},
			} satisfies Preset.Options,
		],
	],

	themeConfig: {
		colorMode: {
			respectPrefersColorScheme: true,
		},
		navbar: {
			title: "KatanaKit",
			items: [
				{
					type: "docSidebar",
					sidebarId: "docsSidebar",
					position: "left",
					label: "Docs",
				},
				{
					href: "https://play.senseikatana.com",
					label: "Playground",
					position: "right",
				},
			{
				type: "dropdown",
				label: "Releases",
				position: "right",
				// <RELEASES-NAVBAR-ITEMS> — generated by scripts/sync-docs-releases.mjs
				items: [
					{
						label: "v5.1.0",
						href: `https://github.com/senseikatana/katanakit-js/releases/tag/v5.1.0`,
					},
					{
						label: "v5.0.1",
						href: `https://github.com/senseikatana/katanakit-js/releases/tag/v5.0.1`,
					},
					{
						label: "v5.0.0",
						href: `https://github.com/senseikatana/katanakit-js/releases/tag/v5.0.0`,
					},
					{
						label: "v4.0.4",
						href: `https://github.com/senseikatana/katanakit-js/releases/tag/v4.0.4`,
					},
					{
						label: "v4.0.3",
						href: `https://github.com/senseikatana/katanakit-js/releases/tag/v4.0.3`,
					},
					{
						label: "v4.0.2",
						href: `https://github.com/senseikatana/katanakit-js/releases/tag/v4.0.2`,
					},
					{
						label: "v4.0.1",
						href: `https://github.com/senseikatana/katanakit-js/releases/tag/v4.0.1`,
					},
					{
						label: "v4.0.0",
						href: `https://github.com/senseikatana/katanakit-js/releases/tag/v4.0.0`,
					},
				],
				// </RELEASES-NAVBAR-ITEMS>
			},
			{
				href: "https://github.com/senseikatana/katanakit-js",
				label: "GitHub",
				position: "right",
			},
			],
		},
		footer: {
			style: "dark",
			links: [
				{
					title: "Docs",
					items: [
						{
							label: "Getting Started",
							to: "/docs/guides/getting-started",
						},
						{
							label: "Architecture",
							to: "/docs/guides/architecture",
						},
						{
							label: "API Reference",
							to: "/docs/api",
						},
						{
							label: "Changelog",
							to: "/docs/changelog",
						},
					],
				},
				{
					title: "Community",
					items: [
						{
							label: "GitHub",
							href: "https://github.com/senseikatana/katanakit-js",
						},
						{
							label: "Issues",
							href: "https://github.com/senseikatana/katanakit-js/issues",
						},
					],
				},
				{
					title: "More",
					items: [
						{
							label: "Changelog",
							to: "/docs/changelog",
						},
						{
							label: "Roadmap",
							to: "/docs/guides/roadmap",
						},
					],
				},
			],
			copyright: `Copyright © ${new Date().getFullYear()} Sergio Jurado. Built with Docusaurus.`,
		},
		prism: {
			theme: prismThemes.github,
			darkTheme: prismThemes.dracula,
			additionalLanguages: ["bash", "json"],
		},
	} satisfies Preset.ThemeConfig,
};

export default config;
