#!/usr/bin/env node
/**
 * Prepares generated docs content before VitePress runs:
 *
 * 1. Generates the TypeDoc API reference into `docs/api/` (with the
 *    VitePress sidebar JSON used by `docs/.vitepress/config.ts`). The run is
 *    skipped when `src/`, `typedoc.json` and `tsconfig.json` are unchanged.
 * 2. Copies `CHANGELOG.md` to `docs/changelog.md` with YAML frontmatter so
 *    both VitePress and Obsidian read it as a proper page/property.
 *
 * Both outputs are gitignored and regenerated by `bun run docs:dev` /
 * `bun run docs`.
 */
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const API_DIR = join(ROOT, "docs", "api");
const API_INDEX = join(API_DIR, "index.md");
const API_SIDEBAR = join(API_DIR, "typedoc-sidebar.json");
const API_HASH = join(API_DIR, ".cache-hash");
const TYPEDOC_BIN = join(ROOT, "node_modules", ".bin", "typedoc");

/** Hashes `src/**` + the TypeDoc/TS config so TypeDoc only runs when needed. */
function sourcesHash() {
	const hash = createHash("sha256");
	for (const file of ["typedoc.json", "tsconfig.json", "scripts/typedoc-drop-deprecated.mjs"]) {
		hash.update(readFileSync(join(ROOT, file)));
	}

	const walk = (dir) => {
		const entries = readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
			a.name.localeCompare(b.name),
		);
		for (const entry of entries) {
			const full = join(dir, entry.name);
			if (entry.isDirectory()) {
				walk(full);
			} else if (entry.name.endsWith(".ts")) {
				hash.update(relative(ROOT, full));
				hash.update(readFileSync(full));
			}
		}
	};
	walk(join(ROOT, "src"));

	return hash.digest("hex");
}

const hash = sourcesHash();
const isCached =
	existsSync(API_INDEX) &&
	existsSync(API_SIDEBAR) &&
	existsSync(API_HASH) &&
	readFileSync(API_HASH, "utf8").trim() === hash;

if (isCached) {
	console.log("docs: docs/api/ is up to date (TypeDoc skipped)");
} else {
	if (!existsSync(TYPEDOC_BIN)) {
		console.error("docs: TypeDoc is not installed — run `bun install` first.");
		process.exit(1);
	}
	try {
		execFileSync(TYPEDOC_BIN, [], { cwd: ROOT, stdio: "inherit" });
	} catch {
		console.error(
			"docs: TypeDoc failed. If it mentions docs/.vitepress/.temp, stop `bun run docs:dev` and retry.",
		);
		process.exit(1);
	}
	writeFileSync(API_HASH, hash);
	console.log("docs: generated docs/api/");
}

const changelog = readFileSync(join(ROOT, "CHANGELOG.md"), "utf8").replace(/^# Changelog\n+/, "");

const page = [
	"---",
	"title: Changelog",
	"description: Release history for KatanaKit JS.",
	"---",
	"",
	"# Changelog",
	"",
	changelog,
].join("\n");

const tempPage = `${join(ROOT, "docs", ".changelog.md.tmp")}`;
writeFileSync(tempPage, page);
renameSync(tempPage, join(ROOT, "docs", "changelog.md"));
console.log("docs: wrote docs/changelog.md");

/* ──────────────────────────────────────────────────────────────────────────
 * 3. Build-time signals for the VitePress theme (`theme/signals.json`):
 *    navbar version pill, GitHub stars, sidebar `new` pills and the
 *    bottom-right "What's new" changelog panel. Every field degrades to a
 *    null/empty value instead of failing the build.
 * ──────────────────────────────────────────────────────────────────────── */

const SIGNALS_FILE = join(ROOT, "docs", ".vitepress", "theme", "signals.json");

function markdownToHtml(text) {
	return text
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;")
		.replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, '<a href="$2">$1</a>')
		.replace(/`([^`]+)`/g, "<code>$1</code>")
		.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
}

/** Newest `## [x.y.z] - date` section of CHANGELOG.md, grouped by `### Heading`. */
function latestChangelog() {
	const text = readFileSync(join(ROOT, "CHANGELOG.md"), "utf8");
	const heading = /^## \[([^\]]+)\] - (\d{4}-\d{2}-\d{2})[ \t]*$/m.exec(text);
	if (!heading) return null;

	const rest = text.slice(heading.index + heading[0].length);
	const nextHeading = rest.search(/\n## \[/);
	const body = nextHeading === -1 ? rest : rest.slice(0, nextHeading);

	const sections = [];
	let current = null;
	for (const rawLine of body.split(/\r?\n/)) {
		const line = rawLine.trimEnd();
		if (/^###\s+/.test(line)) {
			current = { title: line.replace(/^###\s+/, "").trim(), items: [] };
			sections.push(current);
			continue;
		}
		if (/^-\s+/.test(line)) {
			current ??= { title: "Changed", items: [] };
			if (!sections.includes(current)) sections.push(current);
			current.items.push(markdownToHtml(line.replace(/^-\s+/, "")));
		}
	}

	const used = sections.filter((section) => section.items.length > 0);
	return used.length ? { version: heading[1], date: heading[2], sections: used } : null;
}

/** Docs pages changed in the current release cycle, as site routes. */
function newPagePaths() {
	const run = (...args) => {
		try {
			return execFileSync("git", args, {
				cwd: ROOT,
				encoding: "utf8",
				maxBuffer: 32 * 1024 * 1024,
			});
		} catch {
			return "";
		}
	};

	const tags = run("tag", "--sort=-v:refname")
		.split("\n")
		.map((tag) => tag.trim())
		.filter((tag) => /^v\d+\.\d+\.\d+$/.test(tag));
	// Badges cover the cycle that is shipping now: everything touched since the
	// previous release, so they reset when a new version goes out.
	const range = tags[1] ? `${tags[1]}..HEAD` : "";
	const tracked = range
		? run("diff", "--name-only", range, "--", "docs")
		: run("log", "-1", "--name-only", "--pretty=format:", "--", "docs");
	const untracked = run("ls-files", "--others", "--exclude-standard", "--", "docs");

	const pages = new Set();
	for (const line of `${tracked}\n${untracked}`.split("\n")) {
		const file = line.trim();
		if (!file.startsWith("docs/") || !file.endsWith(".md")) continue;
		if (!existsSync(join(ROOT, file))) continue;
		let route = `/${file.slice("docs/".length).replace(/\.md$/, "")}`;
		if (route.endsWith("/index")) route = route.slice(0, -"index".length);
		if (route.length > 1 && route.endsWith("/")) route = route.slice(0, -1);
		pages.add(route || "/");
	}
	pages.delete("/changelog");
	return [...pages].sort();
}

/** Star count, fetched once per build so the site never hits the API. */
async function githubStars() {
	try {
		const response = await fetch("https://api.github.com/repos/senseikatana/katanakit-js", {
			headers: { Accept: "application/vnd.github+json", "User-Agent": "katanakit-docs-build" },
			signal: AbortSignal.timeout(6_000),
		});
		if (response.ok) {
			const data = await response.json();
			if (typeof data.stargazers_count === "number") return data.stargazers_count;
		}
	} catch {
		/* offline or rate-limited — the badge stays hidden */
	}
	return null;
}

/** Version shown in the navbar pill: the newest tag wins over package.json. */
function releasedVersion() {
	try {
		const tag = execFileSync("git", ["tag", "--sort=-v:refname"], { cwd: ROOT, encoding: "utf8" })
			.split("\n")
			.map((line) => line.trim())
			.find((line) => /^v\d+\.\d+\.\d+$/.test(line));
		if (tag) return tag.slice(1);
	} catch {
		/* fall through to package.json */
	}
	return JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")).version;
}

const signals = {
	version: releasedVersion(),
	stars: await githubStars(),
	newPages: newPagePaths(),
	changelog: latestChangelog(),
};

mkdirSync(dirname(SIGNALS_FILE), { recursive: true });
writeFileSync(SIGNALS_FILE, `${JSON.stringify(signals, null, "\t")}\n`);
console.log(
	`docs: signals → version ${signals.version}, stars ${signals.stars ?? "n/a"}, ` +
		`${signals.newPages.length} new page(s)${signals.changelog ? `, changelog v${signals.changelog.version}` : ""}`,
);
