#!/usr/bin/env node
/**
 * Prepares generated docs content before VitePress runs:
 *
 * 1. Generates the TypeDoc API reference into `docs/api/` (with the
 *    VitePress sidebar JSON used by `docs/.vitepress/config.ts`).
 * 2. Copies `CHANGELOG.md` to `docs/changelog.md` with YAML frontmatter so
 *    both VitePress and Obsidian read it as a proper page/property.
 *
 * Both outputs are gitignored and regenerated by `bun run docs:dev` /
 * `bun run docs:build`.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

execFileSync("bunx", ["typedoc"], { cwd: ROOT, stdio: "inherit" });

const changelog = readFileSync(join(ROOT, "CHANGELOG.md"), "utf8").replace(/^# Changelog\n+/, "");

const page = [
	"---",
	"title: Changelog",
	"description: Release history for KatanaKit JS.",
	"---",
	"",
	"# Changelog",
	"",
	changelog,
].join("\n");

writeFileSync(join(ROOT, "docs", "changelog.md"), page);
console.log("docs: generated docs/api/ and docs/changelog.md");
