import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Manual guides + changelog; API tree is generated by TypeDoc into `docs/api`.
 */
const sidebars: SidebarsConfig = {
	docsSidebar: [
		{
			type: "category",
			label: "Guides",
			collapsed: false,
			items: [
				"guides/getting-started",
				"guides/query-client",
				"guides/framework-adapters",
				"guides/watch",
				"guides/architecture",
				"guides/roadmap",
			],
		},
		{
			type: "category",
			label: "UI Kit",
			collapsed: true,
			link: {
				type: "doc",
				id: "ui-kit/index",
			},
			items: [
				"ui-kit/architecture",
				"ui-kit/inventory",
				"ui-kit/llm-files",
				"ui-kit/roadmap",
			],
		},
		"changelog",
		{
			type: "category",
			label: "API Reference",
			collapsed: true,
			link: {
				type: "doc",
				id: "api/index",
			},
			items: [
				{
					type: "autogenerated",
					dirName: "api",
				},
			],
		},
	],
};

export default sidebars;
