import type { VersionEntry } from "./types.js";

/**
 * Auto-generated by archive-docs-version.sh — do not edit manually.
 *
 * Each entry represents an archived documentation version.
 * The starlight-versions plugin reads this to populate the version selector.
 */
export const versions: readonly VersionEntry[] = [];
